server:
  RunMode: debug
  HttpPort: 8081
  ReadTimeout: 60
  WriteTimeout: 60
database:
  DBType: postgres
  Username: username  # 填写你的数据库账号
  Password: 123456  # 填写你的数据库密码
  Host: 127.0.0.1:5432
  DBName: task_scheduling
  TablePrefix: task_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30

